{
  "hash": "bf12a5730992ca76f0cdf498f027ddbe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Analisi Statistiche BPD\"\nauthor: \"Lorenzo Atzeni\"\neditor: visual\nformat:\n  html:\n    self-contained: true\n    number-sections: false\n---\n\n\n\n\n## Data Cleaning\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nDurante l'ispezione del dataset originale, ho notato che alcuni soggetti presentavano lo stesso ID (\"TRAKCARE\"), probabilmente un codice predefinito del software utilizzato per la raccolta dati. Per garantire l'univocità degli identificativi, ho assegnato a questi soggetti un nuovo codice nel formato \"LA\" seguito da un numero progressivo.\n\nVerifichiamo che ora ogni soggetto abbia un ID univoco:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_ID<-df_raw %>% count(df_raw$ID)\nsummary(check_ID)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  df_raw$ID               n    \n Length:99          Min.   :1  \n Class :character   1st Qu.:1  \n Mode  :character   Median :1  \n                    Mean   :1  \n                    3rd Qu.:1  \n                    Max.   :1  \n```\n\n\n:::\n:::\n\n\n\n\nIl controllo conferma che tutti gli ID sono ora univoci (ogni soggetto compare una sola volta).\n\nI nomi delle colonne nel dataset originale contenevano parentesi e caratteri speciali (ad esempio spazi, simboli come `%`, `/`), che possono creare problemi nella manipolazione dei dati in R. Ho quindi rinominato le colonne rimuovendo questi caratteri.\n\nInoltre, il dataset si presenta in formato *wide* (una riga per soggetto, con colonne separate per ogni timepoint). Per l'analisi longitudinale è necessario convertirlo in formato *long* (una riga per ogni osservazione, con una colonna che identifica il timepoint).\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nControlliamo adesso il numero di osservazioni che abbiamo per ciascun timepoint.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_long %>%\n  filter(!is.na(tPTEF_perc_tE)) %>%\n  distinct(ID, timepoint) %>%\n  count(timepoint)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  timepoint     n\n      <int> <int>\n1         1    99\n2         2    64\n3         3    32\n4         4    21\n5         5     5\n6         6     1\n```\n\n\n:::\n:::\n\n\n\n\nVediamo che abbiamo 99 osservazioni dell'outocome di interesse **tPTEF_perc_tE** al primo timepoint; poi 64 al secondo e 32 al terzo.\n\nPer una visualizzazione più immediata:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\nVediamo come si distribuisce l'outcome di interesse primario: tPTEF/Te % che nel nostro dataset è stato rinominato in tPTEF_perc_tE.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\nDal grafico si vede che tPTEF%tE ha una distribuzione **asimmetrica positiva** (coda/skewed a destra). Questa forma è coerente con la scelta di fittare **un GLMM** (Generalized Linear Mixed Model) con family **Gamma** e **link log**, che gestisce bene variabili continue, positive e con asimmetria positiva.\n\n## Modello ad effetti misti GLMM\n\nStimiamo un *mixed model* per rispondere alla domanda di ricerca principale e fare valutazione della funzione respiratoria nei neonati con e senza broncodisplasia.\n\nDataset su cui stimeremo il modello:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_mod <- df_long %>%\n  filter(!is.na(Time), !is.na(tPTEF_perc_tE),!is.na(PH)) %>%\n  mutate(\n    ID = factor(ID),\n    \n    BPD = factor(BPD_Jensen, levels = c(0,1)),#0=No;1=YES\n    sex = factor(sex1M2F, levels = c(1,2)),#1=M;2=F\n    \n    LOS = factor(LOS),\n    PH  = factor(PH),\n    GA=  as.numeric(EG),\n    hsPDA = as.numeric(HSPDAgg)\n    \n    )\n```\n:::\n\n\n\n\nIdealmente, il modello \"migliore\" avrebbe slope ed intercetta random (1 + Time \\| ID).\n\nNel termine `(1 + Time | ID)`:\n\n-   (**1 \\| ID)** = ogni soggetto ha una propria intercetta: consente livelli medi diversi di tPTEF%tE tra bambini.\n\n-   **(Time \\| ID)** = **quanto cambia nel tempo ogni partecipante**, cioè la sua “traiettoria”. E' ragionevole supporre che ogni neonato abbia una diversa pendenza.\n\n    Questa specifica è utile se i dati contengono informazione sufficiente per stimare variazione inter-individuale nelle traiettorie.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_level <- glmmTMB(\n  tPTEF_perc_tE ~ Time + BPD*HSPDAgg + GA + sex + LOS + PH +\n    (1 + Time | ID),\n  family = Gamma(link = \"log\"),\n  data = df_mod\n)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: Gamma  ( log )\nFormula:          \ntPTEF_perc_tE ~ Time + BPD * hsPDA + GA + sex + LOS + PH + (1 |      ID)\nData: df_mod\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   1242.5    1278.6    -610.2    1220.5       186 \n\nRandom effects:\n\nConditional model:\n Groups Name        Variance Std.Dev.\n ID     (Intercept) 0.0467   0.2161  \nNumber of obs: 197, groups:  ID, 84\n\nDispersion estimate for Gamma family (sigma^2): 0.0578 \n\nConditional model:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.786531   0.537290   3.325 0.000884 ***\nTime        -0.003242   0.003240  -1.001 0.316993    \nBPD1        -0.121165   0.086747  -1.397 0.162484    \nhsPDA       -0.007881   0.014938  -0.528 0.597786    \nGA           0.044650   0.018334   2.435 0.014875 *  \nsex2         0.152102   0.068168   2.231 0.025662 *  \nLOS1         0.037262   0.069289   0.538 0.590732    \nPH1         -0.222199   0.078083  -2.846 0.004432 ** \nBPD1:hsPDA   0.008528   0.016576   0.514 0.606923    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nFacendo la diagnostica della parte random si vede che la varianza della slope random di `Time` è praticamente nulla (≈ 0.000014) e la correlazione intercetta–slope è stimata a -1.00. Questo pattern indica che i dati **non supportano** una stima affidabile della slope random (modello “troppo complesso” rispetto all’informazione disponibile), e quindi la specifica più appropriata per l’analisi principale è il **random intercept** `(1 | ID)`.I l modello cheha una parte “random” troppo complessa rispetto all’informazione nei dati, quindi alcuni parametri dei random effects finiscono “sul bordo” (≈ 0) o diventano perfettamente collineari......\n\nRifittiamo quindi il modello con la sola intercetta random **(1 \\| ID).**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_level0 <- glmmTMB(\n  tPTEF_perc_tE ~ Time + BPD*hsPDA + GA + sex + LOS + PH +\n    (1 |  ID),\n  family = Gamma(link = \"log\"),\n  data = df_mod\n)\n```\n:::\n\n\n\n\nCome prima cosa andiamo a vedere i residui e gli assunti:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Mixed Models\n\n  Conditional R2: 0.574\n     Marginal R2: 0.220\n```\n\n\n:::\n:::\n\n\n\n\nCome possiamo vedere dal posterior predictive check il modello **riproduce bene la distribuzione** di `tPTEF_perc_tE` quindi la scelta di un GLM con family Gamma sembra essere stata corretta. Probabilmente un LMM (si potrebbe fare anche una prova) non sarebbe riuscito a predirre cosi bene i valori, e avrebbe predetto valori negativi dell' indice di respirazione che però è solo positivo. Inoltre, la diagnostica di uniformità dei residui simulati mostra un’aderenza soddisfacente alla diagonale attesa, supportando l’adeguatezza della specificazione del modello.\n\nPossiamo quindi guardare i coefficienti:\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: Gamma  ( log )\nFormula:          \ntPTEF_perc_tE ~ Time + BPD * hsPDA + GA + sex + LOS + PH + (1 |      ID)\nData: df_mod\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   1242.5    1278.6    -610.2    1220.5       186 \n\nRandom effects:\n\nConditional model:\n Groups Name        Variance Std.Dev.\n ID     (Intercept) 0.0467   0.2161  \nNumber of obs: 197, groups:  ID, 84\n\nDispersion estimate for Gamma family (sigma^2): 0.0578 \n\nConditional model:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.786531   0.537290   3.325 0.000884 ***\nTime        -0.003242   0.003240  -1.001 0.316993    \nBPD1        -0.121165   0.086747  -1.397 0.162484    \nhsPDA       -0.007881   0.014938  -0.528 0.597786    \nGA           0.044650   0.018334   2.435 0.014875 *  \nsex2         0.152102   0.068168   2.231 0.025662 *  \nLOS1         0.037262   0.069289   0.538 0.590732    \nPH1         -0.222199   0.078083  -2.846 0.004432 ** \nBPD1:hsPDA   0.008528   0.016576   0.514 0.606923    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nIl modello stima:\n\nlog(E\\[Y\\])=β0​+β1​Time+β2​BPD+β3​hsPDA+β4​GA+⋯+β9​(BPD×hsPDA)\n\ndove Y=`tPTEF_perc_tE`.\n\nQuindi: i coefficienti sono su scala logaritmica. Per interpretarli in termini di variazione percentuale:\n\n-   Se fai `exp(β)`, ottieni un **moltiplicatore** della media attesa di Y\n\nInterpretazione pratica:\n\n-   `exp(β) = 1.05` ⇒ circa **+5%** nell’outcome atteso per +1 unità del predittore.\n\n-   `exp(β) = 0.80` ⇒ circa **−20%** nell’outcome atteso.\n\nVediamo coefficiente ***Time***: Per ogni mese in più di età, il tPTEF%tE diminuisce in media dello 0.32%, mantenendo costanti BPD, esposizione a hsPDA, età gestazionale, sesso, sepsi tardiva e ipertensione polmonare. Tuttavia, questo effetto non è statisticamente significativo (p = 0.317), quindi non abbiamo evidenza sufficiente per affermare che ci sia una variazione sistematica nel tempo della funzionalità respiratoria.\n\ncoefficiente **BPD:** I neonati con broncodisplasia (BPD) presentano in media un tPTEF%tE inferiore dell'11.4% rispetto ai neonati senza BPD, **in assenza di esposizione a hsPDA** (hsPDA = 0 giorni), mantenendo costanti età corretta, età gestazionale, sesso, sepsi tardiva e ipertensione polmonare. Tuttavia, questa differenza non raggiunge la significatività statistica (p = 0.162).\n\nNei neonati senza BPD, ogni giorno aggiuntivo di esposizione a **hsPDA** è associato a una riduzione media dello 0.79% nel tPTEF%tE, mantenendo costanti età corretta, BPD, età gestazionale, sesso, sepsi tardiva e ipertensione polmonare. Anche questo effetto non è statisticamente significativo (p = 0.598).\n\n**Per l'interazione BPD × hsPDA:** L'effetto dell'esposizione a hsPDA non differisce in modo statisticamente significativo tra neonati con e senza BPD (p = 0.607). Nei neonati con BPD, ogni giorno aggiuntivo di hsPDA è associato a un cambiamento trascurabile (+0.065%) rispetto all'effetto osservato nei neonati senza BPD.\n\nCoefficienti statisticamente significativi:\n\n**1. Età gestazionale (GA):**\n\nPer ogni settimana in più di età gestazionale alla nascita, il tPTEF%tE aumenta in media del **4,6%** , mantenendo costanti età corretta, BPD, esposizione a hsPDA, sesso, sepsi tardiva e ipertensione polmonare. Questo effetto è statisticamente significativo.\n\n**2. Sesso femminile (sex2):**\n\nI neonati di sesso femminile presentano in media un tPTEF%tE superiore del **16,4%** rispetto ai maschi, mantenendo costanti età corretta, BPD, esposizione a hsPDA, età gestazionale, sepsi tardiva e ipertensione polmonare. Questo effetto è statisticamente significativo (p = 0,026).\n\n**3. Ipertensione polmonare (PH1):**\n\nLa presenza di ipertensione polmonare è associata a una riduzione media del **19,9%** nel tPTEF%tE, mantenendo costanti età corretta, BPD, esposizione a hsPDA, età gestazionale, sesso e sepsi tardiva. Questo effetto è statisticamente significativo (p = 0,004).\n\n## **Modello Traiettorie**\n\nAdesso stimiamo il modello con interazione Time per capire meglio le traiettorie del tempo. In particolare rispondiamo alla domanda:\n\nLe associazioni di BPD e hsPDA con tPTEF%tE cambiano con l’età corretta? Cioè le traiettorie nel tempo differiscono tra gruppi?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_traj <- glmmTMB(\n  tPTEF_perc_tE ~ Time * BPD * hsPDA + GA + sex + LOS + PH +\n    (1 | ID),\n  family = Gamma(link = \"log\"),\n  data = df_mod)\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nDiagnostiche:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(m_traj)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=100%}\n:::\n\n```{.r .cell-code}\nr2(m_traj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Mixed Models\n\n  Conditional R2: 0.582\n     Marginal R2: 0.225\n```\n\n\n:::\n:::\n\n\n\n\nGuardiamo i coefficienti:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m_traj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: Gamma  ( log )\nFormula:          \ntPTEF_perc_tE ~ Time * BPD * hsPDA + GA + sex + LOS + PH + (1 |      ID)\nData: df_mod\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   1247.0    1293.0    -609.5    1219.0       183 \n\nRandom effects:\n\nConditional model:\n Groups Name        Variance Std.Dev.\n ID     (Intercept) 0.04735  0.2176  \nNumber of obs: 197, groups:  ID, 84\n\nDispersion estimate for Gamma family (sigma^2): 0.0569 \n\nConditional model:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)      1.8226169  0.5415605   3.365 0.000764 ***\nTime            -0.0028416  0.0058931  -0.482 0.629667    \nBPD1            -0.1488934  0.1012522  -1.471 0.141421    \nhsPDA           -0.0059798  0.0173848  -0.344 0.730869    \nGA               0.0433141  0.0184187   2.352 0.018691 *  \nsex2             0.1551783  0.0684974   2.265 0.023484 *  \nLOS1             0.0327334  0.0697882   0.469 0.639042    \nPH1             -0.2268675  0.0785878  -2.887 0.003892 ** \nTime:BPD1        0.0048808  0.0084168   0.580 0.561987    \nTime:hsPDA      -0.0003374  0.0013563  -0.249 0.803533    \nBPD1:hsPDA       0.0121787  0.0194311   0.627 0.530814    \nTime:BPD1:hsPDA -0.0009297  0.0017207  -0.540 0.588997    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nQuesto modello include le interazioni con `Time` per verificare se l’associazione di BPD e/o hsPDA con tPTEF%tE **cambia in funzione dell’età corretta**. In particolare:\n\n-   `Time:BPD1` testa se la differenza BPD vs non-BPD varia con l’età (traiettorie non parallele tra BPD e non-BPD).`Time:BPD1` = 0.00488, p = 0.562. Interpretazione (scala log, quindi moltiplicativa): `exp(0.00488) ≈ 1.0049` → **+0.49% per mese.**\n\n    -   Significato: la differenza tra BPD e non-BPD **tenderebbe** ad attenuarsi/aumentare di circa mezzo punto percentuale per mese (a hsPDA=0), **ma** l’evidenza è debole (p=0.56). Non emerge evidenza che l’effetto della BPD vari con l’età corretta; le traiettorie BPD vs non-BPD risultano compatibili con andamenti paralleli.\n\n-   `Time:hsPDA` testa se l’effetto di hsPDA varia con l’età nei non-BPD. exp(−0.000337) ≈ 0.99966 → −0.034% quindi **−0.034% per mese per ogni giorno di hsPDA.** Significato: nei non-BPD, l’effetto di hsPDA **non** sembra cambiare al crescere dell’età (praticamente zero; p=0.80). Non emerge evidenza che l’associazione hsPDA→tPTEF%tE nei non-BPD sia diversa a età più basse vs più alte.\n\n-   `Time:BPD1:hsPDA` testa se la modificazione dell’effetto di hsPDA da parte della BPD **dipende dall’età** (cioè se l’eventuale interazione BPD×hsPDA è diversa a età più basse vs più alte). L' interazione tripla `Time×BPD×hsPDA` non è significativo (p=0.589), indicando che non emerge evidenza che la modificazione dell’effetto di hsPDA da parte della BPD cambi con l’età corretta. In altre parole, l’eventuale differenza nell’effetto di hsPDA tra BPD e non-BPD appare sostanzialmente costante lungo il follow-up.\n\nVerifichiamo quale tra i due modelli è migliore tra m_traj che ha l interazione con Time ed il modello principale m_level0.\n\nFacciamo il confronto dei due modelli tramite Likelihood Ratio Test (LRT):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m_level0, m_traj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: df_mod\nModels:\nm_level0: tPTEF_perc_tE ~ Time + BPD * hsPDA + GA + sex + LOS + PH + (1 | , zi=~0, disp=~1\nm_level0:     ID), zi=~0, disp=~1\nm_traj: tPTEF_perc_tE ~ Time * BPD * hsPDA + GA + sex + LOS + PH + (1 | , zi=~0, disp=~1\nm_traj:     ID), zi=~0, disp=~1\n         Df    AIC    BIC  logLik deviance  Chisq Chi Df Pr(>Chisq)\nm_level0 11 1242.5 1278.6 -610.25   1220.5                         \nm_traj   14 1247.0 1293.0 -609.50   1219.0 1.4996      3     0.6824\n```\n\n\n:::\n:::\n\n\n\n\n**AIC** (*Akaike Information Criterion*) e **BIC** (*Bayesian Information Criterion*) bilanciano la bontà del fit con una penalità per la complessità del modello (AIC e BIC più bassi = modello migliore).\n\nAIC: 1230.8 vs 1235.3 → favorisce m_level0 quindi il modello senza interazione con Time.\n\nBIC: 1266.8 vs 1281.1 → favorisce m_level0 (differenza di \\~14 punti, sostanziale)\n\nLRT: χ² = 1.52, df = 3, p = 0.68 → l'interazione tripla con il tempo non aggiunge nulla\n\nIl modello con interazioni con Time (`m_traj`) non migliora il fit rispetto al modello parsimonioso (`m_level0`): AIC e BIC risultano maggiori per `m_traj`, e il confronto tra modelli nidificati tramite LRT non è significativo (p = 0.68). Pertanto, per l’interpretazione principale riportiamo `m_level0`, che assume effetti costanti nel tempo e risulta supportato dai dati.\n\n## **Modello Interazione PH**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_ph <- glmmTMB(\n  tPTEF_perc_tE ~ Time+ PH * BPD * hsPDA + GA + sex + LOS +\n    (1 | ID),\n  family = Gamma(link = \"log\"),\n  data = df_mod\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nm_ph <- models$m_ph\nsummary(m_ph)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: Gamma  ( log )\nFormula:          \ntPTEF_perc_tE ~ Time + PH * BPD * hsPDA + GA + sex + LOS + (1 |      ID)\nData: df_mod\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   1246.6    1292.6    -609.3    1218.6       183 \n\nRandom effects:\n\nConditional model:\n Groups Name        Variance Std.Dev.\n ID     (Intercept) 0.0452   0.2126  \nNumber of obs: 197, groups:  ID, 84\n\nDispersion estimate for Gamma family (sigma^2): 0.0577 \n\nConditional model:\n                Estimate Std. Error z value Pr(>|z|)   \n(Intercept)     1.730684   0.538504   3.214  0.00131 **\nTime           -0.002851   0.003247  -0.878  0.38003   \nPH1            -0.068613   0.313829  -0.219  0.82694   \nBPD1           -0.065364   0.096641  -0.676  0.49881   \nhsPDA          -0.007716   0.014852  -0.520  0.60337   \nGA              0.046210   0.018334   2.521  0.01172 * \nsex2            0.149442   0.068109   2.194  0.02822 * \nLOS1            0.032181   0.071103   0.453  0.65084   \nPH1:BPD1       -0.240826   0.331110  -0.727  0.46702   \nPH1:hsPDA       0.023293   0.151369   0.154  0.87770   \nBPD1:hsPDA      0.003950   0.018311   0.216  0.82920   \nPH1:BPD1:hsPDA -0.014578   0.152571  -0.096  0.92388   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nGrafico:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=100%}\n:::\n:::\n\n\n\n\nIl grafico mostra le predizioni aggiustate di tPTEF%tE lungo l'età corretta (mesi) ottenute dal modello `m_traj`, che include interazioni tripla con il tempo. Le aree semitrasparenti rappresentano gli intervalli di confidenza al 95%, la cui ampiezza riflette l'incertezza statistica (maggiore dove i dati sono scarsi).\n\nLe curve sono state calcolate fissando le covariate a valori di riferimento: `hsPDA` al suo valore mediano, `GA` alla media campionaria, e le variabili categoriali (`sex`, `LOS`) alla modalità più frequente.\n\n**Interpretazione:**\n\n-   La presenza di PH (linee tratteggiate) è associata a valori predetti sistematicamente più bassi di tPTEF%tE, coerentemente con l'effetto significativo osservato nel modello (p = 0.004).\n\n-   **Nota importante**: Sebbene le curve per BPD e non-BPD mostrino un andamento visivamente divergente, l'interazione statistica `Time × BPD` nel modello **non è risultata significativa** (p = 0.562). Ciò indica che la differenza nelle traiettorie temporali tra i due gruppi è compatibile con la variabilità casuale e non supporta l'ipotesi di un'evoluzione differenziale nel tempo.\n\nLa figura rappresenta quindi le predizioni medie di popolazione (effetti fissi), ma la sovrapposizione delle bande di confidenza e il test statistico formale suggeriscono che le traiettorie di BPD e non-BPD sono sostanzialmente parallele nell'intervallo di tempo osservato.\n\n### Analisi sensitività\n\nFittiamo il modello principale m_level0 togliendo GA e mettendo BW ovvero Peso Nascita:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_sens_BW <- glmmTMB(\n  tPTEF_perc_tE ~ Time + BPD * hsPDA + PN + sex + LOS + PH + (1 | ID),\n  family = Gamma(link = \"log\"),\n  data = df_mod\n)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: Gamma  ( log )\nFormula:          \ntPTEF_perc_tE ~ Time + BPD * hsPDA + PN + sex + LOS + PH + (1 |      ID)\nData: df_mod\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n   1240.8    1276.9    -609.4    1218.8       186 \n\nRandom effects:\n\nConditional model:\n Groups Name        Variance Std.Dev.\n ID     (Intercept) 0.04644  0.2155  \nNumber of obs: 197, groups:  ID, 84\n\nDispersion estimate for Gamma family (sigma^2): 0.0572 \n\nConditional model:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  2.5693987  0.4841221   5.307 1.11e-07 ***\nTime        -0.0029235  0.0032265  -0.906  0.36488    \nBPD1        -0.1054903  0.1156835  -0.912  0.36183    \nhsPDA       -0.0053446  0.0186252  -0.287  0.77415    \nPN           0.0004226  0.0004004   1.055  0.29130    \nsex2         0.1576601  0.0923073   1.708  0.08764 .  \nLOS1         0.0476381  0.0793913   0.600  0.54848    \nPH1         -0.2303915  0.0825728  -2.790  0.00527 ** \nBPD1:hsPDA   0.0061779  0.0190059   0.325  0.74514    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nPer verificare la robustezza dei risultati rispetto all’aggiustamento per maturità alla nascita, abbiamo rifittato il modello principale sostituendo GA con il peso alla nascita (PN/BW). Le stime per BPD, hsPDA e la loro interazione rimangono coerenti (assenza di evidenza statistica), così come l’assenza di un trend temporale. L’associazione negativa con PH risulta stabile. Nel complesso, le conclusioni principali non dipendono dalla scelta GA vs BW come covariata di aggiustamento.\n\n<a href=\"outcome_secondari.html\" class=\"btn btn-primary\">Pagina successiva →</a>\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}